updating user profile, added birth date
la-venganza/ubademy-mobile pull request #12
Opened 2021-11-09 23:08 UTC by Luciana123

- Agrego birth date con su update,
- bug fix de la parte de update del usuario que no se estaba actualizando al guardar la actualizacion.

2021-11-09 23:12 UTC, recheconea requested changes

2021-11-09 23:12 UTC, recheconea commented on src/views/profile.tsx
> +    console.log('called');
comment

2021-11-09 23:12 UTC, recheconea commented on src/views/profileEdit.tsx
> +import DateTimePicker from '@react-native-community/datetimepicker';
no se usa, no? el de arriba tampoco creo

2021-11-09 23:12 UTC, recheconea commented on src/views/profileEdit.tsx
> +        <TextInput
es un input comun y corriente?

2021-11-10 01:04 UTC, Luciana123 commented on src/views/profileEdit.tsx
> +        <TextInput
estaba tratando de ver lo del datePicker pero voy a esperar a que tengan resuelto del back el formato de fechas

2021-11-10 01:04 UTC, Luciana123 commented on src/views/profileEdit.tsx
> +import DateTimePicker from '@react-native-community/datetimepicker';
ya lo saco

2021-11-10 17:55 UTC, recheconea approved these changes

2021-11-11 00:24 UTC, merged