refactor login to centralize all login features in one service
la-venganza/ubademy-mobile pull request #19
Opened 2021-11-15 01:34 UTC by Luciana123

- Refactorizo login cosa que queden todas las llamadas a firebase y al back que involucran el login en una sola clase.

2021-11-15 01:58 UTC, agscontini commented on src/services/loginService.ts
> +  console.log(backUser);
get user no devuelve una promise? que tira aca el console log?

2021-11-15 22:13 UTC, Luciana123 commented on src/services/loginService.ts
> +  console.log(backUser);
claro, devuelve una promise, abajo la trato como promise, se ve que me deje este console para debuggear, ya lo saco

2021-11-15 22:19 UTC, recheconea requested changes
Deje varios comments de cosas que no me terminan de cerrar y de formas de hacer las cosas. Podemos discutirlos, incluso dejarlos asi si no queremos dedicarle mas a esta parte (lo cual tiene sentido) pero no queria dejar de comentarlo.

2021-11-15 22:19 UTC, recheconea commented on src/services/loginService.ts
> +  console.log(backUser);
Devuelve una promise, mas abajo la handlea. Ese console log va a mostrar un objeto promise
Un comentario que aplica a varias partes del file este:
- Estamos usando promises con then y coso, y async await. Deberiamos homogeneizar ahi y llevar todo a async-await.

2021-11-15 22:19 UTC, recheconea commented on src/services/loginService.ts
> +      userService.registerUser(userData);
Tira error si falla? No deberiamos ver la respuesta de este register antes de settear el auth?

2021-11-15 22:19 UTC, recheconea commented on src/services/loginService.ts
> +    console.log(jwt, userName, firebaseCredential.user.email);
Ojo estos logs

2021-11-15 22:19 UTC, recheconea commented on src/services/loginService.ts
> +const loginWithUserAndPassword = async (authCtx: AuthContext, email: string, password: string) => {
Mismo que comentaba antes. Es un metodo async pero que adentro usa la estructura de promises. Esto va a implicar que el codigo va a seguir de largo y no va a parar aca esperando que se resuelva la promise. Depende de como este estructurado el otro lado, puede ser un issue. ojo.

2021-11-15 22:19 UTC, recheconea commented on src/services/loginService.ts
> +        console.log(u);
ojo el log

2021-11-15 22:19 UTC, recheconea commented on src/services/loginService.ts
> +      authCtx.setAuth(jwt, userName, email);
viendo esto y el doble llamado, no estaria bueno que la respeusta del back ya venga con toda la info y no tengas que ir a buscar el id? aca lo sumo a @agscontini y @German-Rotili

2021-11-15 22:19 UTC, recheconea commented on src/services/loginService.ts
> +        userService.registerUser(user);
este createuser le pega al back? no podriamos reducir a una sola llamada?

2021-11-16 00:49 UTC, German-Rotili commented on src/services/loginService.ts
> +      authCtx.setAuth(jwt, userName, email);
Esto se podria resolver usando el ID que provee firebase quizas, asi ya te traes el id en ese llamado? @agscontini

2021-11-16 00:52 UTC, agscontini approved these changes
Yo lo veo bien, ro metio un warning en uno (y coincido en que esta bueno que estandaricemos si vamos con .then o async awaits....

2021-11-16 00:55 UTC, Luciana123 commented on src/services/loginService.ts
> +      authCtx.setAuth(jwt, userName, email);
si se puede hacer que al loguearte, el back te devuelva el ID

2021-11-16 00:56 UTC, Luciana123 commented on src/services/loginService.ts
> +const loginWithUserAndPassword = async (authCtx: AuthContext, email: string, password: string) => {
eso sí, lo único que como la pantalla principal observa el context, eso cuando funca, setea el context y ahi te loguea si el ctx esta seteado

2021-11-16 00:56 UTC, Luciana123 commented on src/services/loginService.ts
> +    console.log(jwt, userName, firebaseCredential.user.email);
gone

2021-11-16 00:56 UTC, Luciana123 commented on src/services/loginService.ts
> +      userService.registerUser(userData);
oka

2021-11-16 00:57 UTC, agscontini commented on src/services/loginService.ts
> +      authCtx.setAuth(jwt, userName, email);
Acá decis de meter como user id, el id que ya te provee firebase? si es único, y todos los usuarios que se crean/loguean pasan por acá y lo tienen, re....tener 2 identificadores únicos representando lo mismo no suma la verdad, podemos cambiar el post para que reciba tmb el user_id y ahi se manda este id, y ya. Sería el que quedaría para representar al user en nuestro dominio

2021-11-16 00:57 UTC, Luciana123 commented on src/services/loginService.ts
> +      userService.registerUser(userData);
ah el tema aca es que si falla el register, después le pide el usuario al back, entonces si no está registrado no te trae el usuario.

2021-11-16 01:01 UTC, agscontini commented on src/services/loginService.ts
> +      authCtx.setAuth(jwt, userName, email);
El id hoy entiendo que se deuvelve, porque cuando se pega al back para crear, si lo crea lo devuelve, y si ya existe, lo devuelve tmb ..

2021-11-16 01:07 UTC, recheconea commented on src/services/loginService.ts
> +      userService.registerUser(userData);
pero no tenes un race condition? porque no estas esperando a que vuelva del register y estas llamando al get inmediatamente despues. deberia tener un await delante de los api call para garantizar que se ejecuten al haberse terminado

2021-11-16 01:07 UTC, recheconea commented on src/services/loginService.ts
> +const loginWithUserAndPassword = async (authCtx: AuthContext, email: string, password: string) => {
Claro, te salva con eso. Quiza lo que si le agregaria (no urgente, ni cerca) es usar el context de loading que cree para dar sensacion de cargando. Nada, solo para tener en cuenta.

2021-11-16 01:07 UTC, recheconea commented on src/services/loginService.ts
> +      authCtx.setAuth(jwt, userName, email);
Entonces habria que ver. o sea, en un contexte real hace el login y luego va a buscar el user, capaz podriamos resolver eso en un solo paso :thinking: 
aclaro de nuevo, no digo de hacerlo. es mas un insight

2021-11-16 23:49 UTC, merged