profile screen mock
la-venganza/ubademy-mobile pull request #8
Opened 2021-10-31 18:40 UTC by Luciana123

- Mock de la plantalla de profile de usuario.

2021-10-31 21:42 UTC, recheconea approved these changes

2021-11-07 15:53 UTC, agscontini commented on src/components/LoginButton/index.tsx
> +            first_name: result.user.givenName,
salvo el email, el resto son opcionales segun recuerdo, pero por qué no te traerías el last name posta si esta?
age lo cambiamos en el back por birth_date...igual eso esta en pr y todavía no se mergeo

2021-11-07 15:55 UTC, agscontini commented on src/interfaces/IUser.ts
> +    age: number,
pasa a ser birth_date el dato..
por otro lado, se sumaron phone_type, phone_number y subscription (que por default cae en Base)
todos opcionales igual

2021-11-07 19:54 UTC, recheconea requested changes
Laburazo, deje unos comments

2021-11-07 19:54 UTC, recheconea commented on src/components/LogOnButton/index.tsx
> +        //const jwt = user.stsTokenManager.accessToken;
Comment

2021-11-07 19:54 UTC, recheconea commented on src/components/LoginButton/index.tsx
> +      //      console.log('Firebase credentials');
Comments

2021-11-07 19:54 UTC, recheconea commented on src/views/registration.tsx
> +            userService.setCookie(auth.currentUser.stsTokenManager.accessToken);
Esta cookie probablemente deberiamos settearla a nivel general y no solo a nivel de userservice, porque va a ser necesaria de manera transversal por toda la app.

2021-11-07 19:54 UTC, recheconea commented on src/components/LoginButton/index.tsx
> +      userService.setCookie(jwt);
Ojo con esto, probablemente deberia estar setteada de forma transversal a la app.

2021-11-07 23:26 UTC, Luciana123 commented on src/components/LoginButton/index.tsx
> +            first_name: result.user.givenName,
claro, mas data en la demo, si no queda algo medio vacio

2021-11-07 23:27 UTC, Luciana123 commented on src/interfaces/IUser.ts
> +    age: number,
joya, en el prox pr lo integro

2021-11-07 23:30 UTC, Luciana123 commented on src/views/registration.tsx
> +            userService.setCookie(auth.currentUser.stsTokenManager.accessToken);
Sí coincido, lo ideal sería setearlo en el auth, el tema es que el usuario no está logueado para esta altura, y yo necesito setearse la cookie para llamar al back (tal vez el endpoint de register no tendría que tener autenticación?)

2021-11-07 23:30 UTC, Luciana123 commented on src/components/LoginButton/index.tsx
> +      userService.setCookie(jwt);
mismo que el otro caso de registro

2021-11-08 00:25 UTC, merged